capstone/capstone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('countermatic/', include('countermatic.urls')),
]

capstone/countermatic/urls.py
from django.urls import path
from .views import home_page, register, login_user, logout_user, vendors, add_vendor, get_vendors, delete_vendor, harvest, dashboard, table

app_name = 'countermatic'
urlpatterns = [
    path('', home_page, name='home'),
    path('register/', register, name="register"),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('vendors/', vendors, name="vendors"),
    path('add-vendor/', add_vendor, name="add-vendor"),
    path('get-vendors/', get_vendors, name="get-vendors"), 
    path('delete-vendor/', delete_vendor, name="delete-vendor"),        
    path('dashboard/', dashboard, name="dashboard"), 
    path('table/', table, name="table"),           
    path('harvest/', harvest, name="harvest"),
]

capstone/countermatic/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Vendor(models.Model):
    vendor_name = models.CharField(max_length = 50)
    sushi_url = models.URLField()
    requestor_id = models.CharField(max_length = 50, null=True, blank=True)
    requestor_name = models.CharField(max_length = 50, null=True, blank=True)
    customer_id = models.CharField(max_length = 50, null=True, blank=True)
    customer_name = models.CharField(max_length = 50, null=True, blank=True)
    user_name = models.CharField(max_length = 50, null=True, blank=True)
    password = models.CharField(max_length = 50, null=True, blank=True)
    requestor_email = models.EmailField(null=True, blank=True)
    api_key = models.CharField(max_length = 75, null=True, blank=True)
    platform = models.CharField(max_length = 50, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="vendors", null=True)

    def __str__(self):
        return self.vendor_name

capstone/countermatic/views.py
from django.http.response import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import Vendor
import datetime, requests
import pycounter

# -----------------------------------------------------
# Homepage
# -----------------------------------------------------
def home_page(request):
    return render(request, 'countermatic/index.html')

# -----------------------------------------------------
# User Management
# -----------------------------------------------------
def register(request):
    print('METHOD', request.method)
    if request.method == "GET":
        return render(request, 'countermatic/register.html')
    elif request.method == "POST":
        print('FORM', request.POST)

        # Get data from our form
        form = request.POST
        username = form['username']
        password = form['password']
        email = form['email']

        # Create user. username, email, password.
        user = User.objects.create_user(
            username, email, password)

        login(request, user)

        return HttpResponseRedirect(reverse('countermatic:home'))

def login_user(request):
    # User visits page
    if request.method == "GET":
        return render(request, 'countermatic/login.html')
    # User submits form
    elif request.method == "POST":
        print('FORM', request.POST)
        # Get form data
        form = request.POST
        username = form['username']
        password = form['password']

        # Authenticate User
        user = authenticate(request, username=username, password=password)
        if user != None:
            login(request, user)

        return HttpResponseRedirect(reverse('countermatic:home'))


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('countermatic:home'))

# -----------------------------------------------------
# Configure Vendors
# -----------------------------------------------------
@login_required
def vendors(request):

    Vendors = Vendor.objects.filter(user=request.user)

    context = {
        'vendors': Vendors,
    }

    return render(request, 'countermatic/vendors.html', context)

@login_required
def add_vendor(request):

    vendor = Vendor()

    form = request.POST

    url = form['sushi_url']
    if url[-1] != "/":
        url += "/"

    vendor.vendor_name = form['vendor_name']
    vendor.sushi_url = url
    vendor.requestor_id = form['requestor_id']
    vendor.requestor_name = form['requestor_name']
    vendor.customer_id = form['customer_id']
    vendor.customer_name = form['customer_name']
    vendor.user_name = form['vnd_username']
    vendor.password = form['vnd_password']
    vendor.requestor_email = form['requestor_email']
    vendor.api_key = form['api_key']
    vendor.platform = form['platform']
    vendor.user = request.user

    vendor.save()

    return HttpResponseRedirect(reverse('countermatic:vendors'))

@login_required
def delete_vendor(request):
    form = request.POST

    vendor_id = form['vendor_id']

    Vendors = Vendor.objects.filter(user=request.user)
    selected_vendor = Vendors.get(id=vendor_id)
    selected_vendor.delete()
    return HttpResponseRedirect(reverse('countermatic:vendors'))

# -----------------------------------------------------
# Harvest Reports
# -----------------------------------------------------
@login_required
def get_vendors(request):
    Vendors = Vendor.objects.filter(user=request.user)

    json = {
        'vendors': []
    }

    for vendor in Vendors:

        vendor_params = {
            'id': vendor.id,
            'base_url':vendor.sushi_url,
        }

        if vendor.customer_id:
            cust_id = vendor.customer_id
            vendor_params["customer_id"] = cust_id
        if vendor.requestor_id:
            request_id = vendor.requestor_id
            vendor_params["requestor_id"] = request_id
        if vendor.api_key:
            api_key = vendor.api_key
            vendor_params["api_key"] = api_key

        json['vendors'].append(vendor_params)

    return JsonResponse(json)

@login_required
def harvest (request):

    if request.method == "GET":
        Vendors = Vendor.objects.all()

        context = {
            'vendors': Vendors,
            'user' : request.user
        }

        return render(request, 'countermatic/harvest.html', context)

    # User submits form
    elif request.method == "POST":
        # Get form data
        form = request.POST
        vendor = form['vendordrop']
        selected_vendor = Vendor.objects.filter(id=vendor)
        report = form['reportdrop']
        datefrom = form['datefrom']
        fromdateobject = datetime.datetime.strptime(datefrom, '%m/%d/%Y').strftime('%Y-%m-%d')
        dateto = form['dateto']
        todateobject = datetime.datetime.strptime(dateto, '%m/%d/%Y').strftime('%Y-%m-%d')
        base_url = selected_vendor[0].sushi_url
        route = form['radioRouter']

        params = {}

        if selected_vendor[0].customer_id:
            cust_id = selected_vendor[0].customer_id
            params["customer_id"] = cust_id
        if selected_vendor[0].requestor_id:
            request_id = selected_vendor[0].requestor_id
            params["requestor_id"] = request_id
        if selected_vendor[0].api_key:
            api_key = selected_vendor[0].api_key
            params["api_key"] = api_key

        request_url = f"{base_url}reports/{report}?begin_date={fromdateobject}&end_date={todateobject}" 
        
        for key, value in params.items():
            request_url += f"&{key}={value}"
            
        response = requests.get(request_url)
        json_response = response.json()


        print("Report Done!")
        print("Starting Parse")
        
        final_py_data = []
        
        for database in json_response["Report_Items"]:
            metric_list = []
            for metric in database['Performance'][0]['Instance']:
                metric_list.append(metric['Metric_Type'])
            for metric in metric_list:
                new_database = {}
                new_database['platform'] = database['Platform']
                new_database['database'] = database['Database']
                new_database['metric'] = metric
                for i in range (len(database["Performance"])):
                    date_key = database["Performance"][i]["Period"]["Begin_Date"]
                    date_key = datetime.datetime.strptime(date_key, '%Y-%m-%d').strftime('%m/%d/%y')
                    for j in range (len(database["Performance"][i]["Instance"])):
                        if database["Performance"][i]["Instance"][j]["Metric_Type"] == metric:
                            data_value = str(database["Performance"][i]["Instance"][j]["Count"])
                    new_database[date_key] = data_value
                final_py_data.append(new_database)

        context = {
            'json_response': final_py_data,
        }

        if route == "radioTable":
            route_url = 'countermatic/table.html'
        else:
            route_url = 'countermatic/dashboard.html'

        return render(request, route_url, context)

# -----------------------------------------------------
# Visualize Reports
# -----------------------------------------------------
@login_required
def dashboard (request):

    return render(request, 'countermatic/dashboard.html')
@login_required
def table (request):

    return render(request, 'countermatic/table.html')

capstone/countermatic/templates/countermatic/_navbar.html
<!-- Navigation -->
<nav>
  <div class="logo"><h1>COUNTERMATIC</h1></div>
  <ul class="nav-links">
    <li><a href="{% url 'countermatic:home' %}">Home</a></li>
    {% if request.user.is_anonymous %}
    <li><a href="{% url 'countermatic:register' %}">Register</a></li>
    <li><a href="{% url 'countermatic:login' %}">Log In</a></li>
    {% else %}
    <li><a>{{request.user}}</a></li>   
    <li><a href="{% url 'countermatic:logout' %}">Log Out</a></li>
    {% endif %}

  </ul>
  <!-- Mobile Navigation -->
  <div class="nav-burger">
    <div class="line1"></div>
    <div class="line2"></div>
    <div class="line3"></div>
  </div>
</nav>

capstone/countermatic/templates/countermatic/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>COUNTERMATIC</title>
    <link rel="stylesheet" href="{% static 'countermatic/style.css' %}" />
    <link
    href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap"
    rel="stylesheet"
  />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <link rel="shortcut icon" type="image/png" href="{% static 'countermatic/favicon.ico' %}"/>
  <script src="https://code.highcharts.com/highcharts.js"></script>
  <script defer src="{% static 'countermatic/app.js' %}"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
  </head>
  <body>
    {% include 'countermatic/_navbar.html' %}
        <div class="main">
          <section class="viewport">
            {% block content %} 
            {% endblock %}
          </section>
        </div>
    </div>
  </body>
</html>

capstone/countermatic/templates/countermatic/dashboard.html
{% extends 'countermatic/base.html' %} 
{% load static %}

{% block content %}
<div class="container">
<div class="row">
    <div class="col">
      <div class="d-flex justify-content-center" style="padding-top: 20px;"><img src="{% static 'countermatic/img/dashboard.png' %}" alt="" style="height: 10rem;"></div></div>
      <div class="d-flex justify-content-center"><h3>Chart View</h3></div>
  </div>
    <div class="p-2 row">
        <div class="col"></div>
        <div class="col-6">
            <select class="form-select" name="" id="select-vendor">
            </select>
        <select class="form-select" name="" id="select-database">
        </select>
        </div>
        <div class="col"></div>
</div>
<div class="p-2 row">
    <div class="col"><div class="container-highcharts" id="chart1"></div></div>
    <div class="col"><div class="container-highcharts" id="chart2"></div></div>
</div>
<div class="p-2 row">
    <div class="col"><div class="container-highcharts" id="chart3"></div></div>
    <div class="col"><div class="container-highcharts" id="chart4"></div></div>
</div>
</div>
<script src="{% static 'countermatic/usage_data.js' %}"></script>
<script defer src="{% static 'countermatic/app_charts.js' %}"></script>
{% endblock %}

capstone/countermatic/templates/countermatic/harvest.html
{% extends 'countermatic/base.html' %} 
{% load static %} 
{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <div class="d-flex justify-content-center" style="padding-top: 20px;"><img src="{% static 'countermatic/img/api.png' %}" alt="" style="height: 10rem;"></div></div>
      <div class="d-flex justify-content-center"><h3>Harvest Data</h3></div>
  </div>
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
<div class="vendorlist">
  <h4 id="vendorHeading">Select a Vendor</h4>
  <form action="{% url 'countermatic:harvest' %}" method="POST" name="harvestForm" onsubmit="return validateSubmit()">
    {% csrf_token %}
    <select
      name="vendordrop"
      id="vendor-drop"
      class="form-select"
      aria-label="Vendor Dropdown"
    >
      <option selected>Select a Vendor</option>
      {% for vendor in user.vendors.all%}
      <option value="{{vendor.id}}">{{vendor.vendor_name}}</option>
      {% endfor %}
    </select>
    <h4 id="reportHeading">Select a Report</h4>
    <select
      name="reportdrop"
      id="report-drop"
      class="form-select"
      aria-label="Report Dropdown"
      disabled
    >
      <option selected>Select a Report</option>
    </select>
    <h4>Date From</h4>

    <input id="datefrom" class="form-control" type="text" name="datefrom" value="" />

    <script>
    $(function() {
      $('input[name="datefrom"]').daterangepicker({
        singleDatePicker: true,
        showDropdowns: true,
        minYear: 1901,
        maxYear: parseInt(moment().format('YYYY'),10)
      });
    });
    </script>
    <h4>Date To</h4>

    <input id="dateto" class="form-control" type="text" name="dateto" value="" />

    <script>
    $(function() {
      $('input[name="dateto"]').daterangepicker({
        singleDatePicker: true,
        showDropdowns: true,
        minYear: 1901,
        maxYear: parseInt(moment().format('YYYY'),10)
      });
    });
    </script>
    
    <h4>Delivery Method</h4>
    <div class="form-check form-check-inline">
      <input class="form-check-input" type="radio" name="radioRouter" id="radioTable" value="radioTable" checked>
      <label class="form-check-label" for="inlineRadio2">Table</label>
    </div>
    <div class="form-check form-check-inline">
      <input class="form-check-input" type="radio" name="radioRouter" id="radioCharts" value="radioCharts">
      <label class="form-check-label" for="inlineRadio3">Charts</label>
    </div>
    <div class="form-check form-check-inline">
      <input class="form-check-input" type="radio" name="radioRouter" id="radioDownload" value="radioDownload" disabled>
      <label class="form-check-label" for="inlineRadio1">Download</label>
    </div>

    <button id="sub_btn" type="submit" type="button" class="btn btn-primary btn-lg btn-block">
      Harvest Report
    </button>
  </form>
</div>
    </div>
    <div class="col-3"></div>    
</div>
<script defer src="{% static 'countermatic/app_harvest.js' %}"></script>
{% endblock %}

capstone/countermatic/templates/countermatic/index.html
{% extends 'countermatic/base.html' %} 
{% load static %}

{% block content %}

<div class="card" style="width: 18rem; height: 20rem; padding-top: 20px;">
  <div class="d-flex justify-content-center"><img class="card-img-top" src="{% static 'countermatic/img/gears.png' %}" alt="Card image cap"></div>
    <div class="card-body">
      <h5 class="card-title">Configure Vendors</h5>
      <p class="card-text">Register and update vendor profiles</p>
      {% if request.user.is_anonymous %}
      <a href="#" class="btn btn-primary disabled">Configure</a>
      {% else %}
      <a href="{% url 'countermatic:vendors' %}" class="btn btn-primary">Configure</a>
      {% endif %}
    </div>
  </div>
  <div class="card" style="width: 18rem; height: 20rem; padding-top: 20px;">
    <div class="d-flex justify-content-center"><img class="card-img-top" src="{% static 'countermatic/img/api.png' %}" alt="Card image cap"></div>
    <div class="card-body">
      <h5 class="card-title">Harvest</h5>
      <p class="card-text">Initiate a COUNTER report harvest and view data</p>
      {% if request.user.is_anonymous %}
      <a href="#" class="btn btn-primary disabled">Harvest</a>
      {% else %}
      <a href="{% url 'countermatic:harvest' %}" class="btn btn-primary">Harvest</a>
      {% endif %}
    </div>
  </div>
  <div class="card" style="width: 18rem; height: 20rem; padding-top: 20px;">
    <div class="d-flex justify-content-center"><img class="card-img-top" src="{% static 'countermatic/img/data.png' %}" alt="Card image cap"></div>
    <div class="card-body">
      <h5 class="card-title">View Data Tables</h5>
      <p class="card-text">View harvested data in a table and export</p>
      <a href="#" class="btn btn-primary disabled">View Tables</a>
    </div>
  </div>
  <div class="card" style="width: 18rem; height: 20rem; padding-top: 20px;">
    <div class="d-flex justify-content-center"><img class="card-img-top" src="{% static 'countermatic/img/dashboard.png' %}" alt="Card image cap"></div>
    <div class="card-body">
      <h5 class="card-title">Data Dashboard</h5>
      <p class="card-text">View data in a dashboard with data visualization</p>
      {% if request.user.is_anonymous %}
      <a href="#" class="btn btn-primary disabled">View Dashboard</a>
      {% else %}
      <a href="{% url 'countermatic:dashboard' %}" class="btn btn-primary">View Dashboard</a>
      {% endif %}
    </div>
  </div>

{% endblock %}

capstone/countermatic/templates/countermatic/login.html
{% extends 'countermatic/base.html' %} 
{% load static %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <div class="d-flex justify-content-center" style="padding-top: 20px;"><img src="{% static 'countermatic/img/log-in.png' %}" alt="" style="height: 10rem;"></div></div>
      <div class="d-flex justify-content-center"><h3>Log In</h3></div>
  </div>
  <div class="row">
    <div class="col"></div>
    <div class="col">
      <form action="{% url 'countermatic:login' %}" method="POST">
          {% csrf_token %}
          <input class="form-control" type="text" name="username" placeholder="Username" required>
          <input class="form-control" type="password" name="password" placeholder="Password" required>
          <button class="btn btn-primary" type="submit">Log In</button>
          <a href="{% url 'countermatic:register' %}">or signup</a>
        </form>
    </div>
    <div class="col"></div>
  </div>

</div>

{% endblock %}

capstone/countermatic/templates/countermatic/register.html
{% extends 'countermatic/base.html' %} 
{% load static %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="d-flex justify-content-center" style="padding-top: 20px;"><img src="{% static 'countermatic/img/register.png' %}" alt="" style="height: 10rem;"></div></div>
        <div class="d-flex justify-content-center"><h3>Sign Up</h3></div>
    </div>
    <div class="row">
      <div class="col"></div>
      <div class="col">
        <form action="{% url 'countermatic:register' %}" method="POST">
          {% csrf_token %}
          <input class="form-control" type="text" name="username" placeholder="Username" required>
          <input class="form-control" type="password" name="password" placeholder="Password" required>
          <input class="form-control" type="email" name="email" placeholder="Email" required>
          <button class="btn btn-primary" type="submit">Sign-Up</button>
        </form>
      </div>
      <div class="col"></div>
    </div>
  
  </div>
{% endblock %}

capstone/countermatic/templates/countermatic/report.html
{% extends 'countermatic/base.html' %} 
{% load static %}

{% block content %}



{% endblock %}

capstone/countermatic/templates/countermatic/table.html
{% extends 'countermatic/base.html' %} {% load static %} {% block content %}
<div class="container">
  <div class="d-flex flex-row bd-highlight mb-3">
    <div class="p-2"><a href="{% url 'countermatic:harvest' %}" class="btn btn-primary"><span>&#8592;</span> Harvest</a></div>
  </div>
  <div class="d-flex flex-column justify-content-center">
    <div class="row">
      <div class="col">
        <div class="d-flex justify-content-center" style="padding-top: 20px;"><img src="{% static 'countermatic/img/data.png' %}" alt="" style="height: 5rem;"></div></div>
        <div class="d-flex justify-content-center"><h3>Harvest Data</h3></div>
    </div>
    <div class="row">
      <div class="col">
        <a
          class="btn btn-primary"
          download="report.xls"
          href="#"
          onclick="return ExcellentExport.excel(this, 'data-table', 'COUNTER_REPORT');"
          >Export to Excel</a
        >
        
        <a
          class="btn btn-primary"
          download="report.csv"
          href="#"
          onclick="return ExcellentExport.csv(this, 'data-table');"
          >Export to CSV</a
        >
      </div>
    </div>
  </div>
  <div class="row">
    <div class="d-flex flex-column justify-content-center">
      <div class="container-table">
        <div class="list_gen" id="title_table">
          <table
            id="data-table"
            class="table table-striped table-hover list"
            width="75%"
          >
            <thead class="thead-dark">
              <tr id="header-row">
                <th scope="col">Platform</th>
                <th scope="col">Database</th>
                <th scope="col">Metric</th>
              </tr>
            </thead>
            <tbody id="table-body"></tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

{{ json_response|json_script:"json_response" }}
<script src="{% static 'countermatic/data.js' %}"></script>
<script src="{% static 'countermatic/excellentexport.js' %}"></script>
<script defer src="{% static 'countermatic/app_tables.js' %}"></script>
{% endblock %}

capstone/countermatic/templates/countermatic/vendors.html
{% extends 'countermatic/base.html' %} 
{% load static %}
{% block content %}
<div class='container'>
  <div class="row">
    <div class="col">
      <div class="d-flex justify-content-center" style="padding-top: 20px;"><img src="{% static 'countermatic/img/gears.png' %}" alt="" style="height: 10rem;"></div></div>
      <div class="d-flex justify-content-center"><h3>Configure Vendors</h3></div>
  </div>
  <div class="row">
  <div class="col-3"></div>
  <div class="col-6">
  <div class='vendorform'>
<form action="{% url 'countermatic:add-vendor'%}" method="POST">
{% csrf_token %}
    <div class="form-row">
      <div class="form-group">
        <label for="vendor_name">Vendor Name</label>
        <input type="text" class="form-control" id="vendor_name" name="vendor_name" placeholder="Vendor Name">
      </div>
      <div class="form-group">
        <label for="sushi_url">Sushi URL</label>
        <input type="text" class="form-control" id="sushi_url" name="sushi_url" placeholder="Sushi URL">
      </div>
    </div>
    <div class="form-group">
      <label for="requestor_id">Requestor ID</label>
      <input type="text" class="form-control" id="requestor_id" name="requestor_id" placeholder="Requestor ID">
    </div>
    <div class="form-group">
      <label for="requestor_name">Requestor Name</label>
      <input type="text" class="form-control" id="requestor_name" name="requestor_name" placeholder="Requestor Name">
    </div>
    <div class="form-group">
        <label for="customer_id">Customer ID</label>
        <input type="text" class="form-control" id="customer_id" name="customer_id" placeholder="Customer ID">
    </div>
    <div class="form-group">
        <label for="customer_name">Customer Name</label>
        <input type="text" class="form-control" id="customer_name" name="customer_name" placeholder="Customer Name">
    </div>
    <div class="form-group">
        <label for="vnd_username">Username</label>
        <input type="text" class="form-control" id="vnd_username" name="vnd_username" placeholder="Username">
    </div>
    <div class="form-group">
        <label for="vnd_username">Password</label>
        <input type="text" class="form-control" id="vnd_password" name="vnd_password" placeholder="Password">
    </div>
    <div class="form-group">
        <label for="requestor_email">Requestor Email</label>
        <input type="email" class="form-control" id="requestor_email" name="requestor_email" placeholder="Requestor Email">
    </div>
    <div class="form-group">
        <label for="api_key">API Key</label>
        <input type="text" class="form-control" id="api_key" name="api_key" placeholder="API Key">
    </div>
    <div class="form-group">
        <label for="platform">Platform</label>
        <input type="text" class="form-control" id="platform" name="platform" placeholder="Platform">
    </div>
    <button type="submit" class="btn btn-primary">Register Vendor</button>
  </form>
</div>
<div class="vendorlist">
<div class="row py-5">
  <div class="col">
    <div class="list_gen" id="title_table">
      <table class="table table-striped table-hover list" width="75%">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Vendor</th>
            <th scope="col"><button class="btn btn-danger btn-sm" id="del-submit" onclick="document.getElementById('del-form').submit();" disabled>Delete</button></th>
          </tr>
        </thead>
        <tbody>
          <form id="del-form" action="{% url 'countermatic:delete-vendor' %}" method="POST">
          {% csrf_token %}
          {% for vendor in vendors.all%}
          <tr>
            <td>{{vendor.vendor_name}}</td>
              <td>
                <input class="form-check-input" type="radio" name="vendor_id" value={{vendor.id}}></td>
              </tr>
              {% endfor %}
            </form>
        </tbody>
      </table>
    </div>
  </div>
</div>
  </div>
</div>
</div>
<div class="col-3"></div>
</div>
<script defer src="{% static 'countermatic/app_vendors.js' %}"></script>
{% endblock %}